---
- name: Install PHP FPM
  apt:
    pkg: "php{{ php_fpm_version }}-fpm"
    state: present
    update_cache: yes
    cache_valid_time: 3600

- name: Install PHP packages
  apt:
    pkg: "{{ php_fpm_packages }}"
    state: present
    update_cache: yes
    cache_valid_time: 3600
  notify: restart php-fpm

- name: Install Xdebug
  apt:
    pkg: "php{{ php_fpm_version }}-xdebug"
    state: present
    update_cache: yes
    cache_valid_time: 3600
  when: php_fpm_xdebug
  notify: restart php-fpm
  register: php_fpm_xdebug_installed

- name: Disable xdebug by default
  file:
    path: "/etc/php/{{ php_fpm_version }}/fpm/conf.d/20-xdebug.ini"
    state: absent

- name: Remove default pool
  file:
    path: "/etc/php/{{ php_fpm_version }}/fpm/pool.d/www.conf"
    state: absent
  notify: restart php-fpm

- name: Apply PHP FPM settings
  template:
    src: "{{ lookup('first_found', [role_path~'/templates/php'~php_fpm_version~'.ini.j2', role_path~'/templates/php.ini.j2']) }}"
    dest: "/etc/php/{{ php_fpm_version }}/fpm/php.ini"
    owner: root
    group: root
    mode: 0644
  notify: restart php-fpm

- name: Apply PHP FPM conf
  template:
    src: php-fpm.conf.j2
    dest: "/etc/php/{{ php_fpm_version }}/fpm/php-fpm.conf"
    owner: root
    group: root
    mode: 0644
  notify: restart php-fpm

- name: Install pools
  template:
    src: "templates/fpm/pools/{{ item.src }}"
    dest: "/etc/php/{{ php_fpm_version }}/fpm/pool.d/{{ item.dest }}"
    owner: root
    group: root
    mode: 0600
  notify: restart php-fpm
  with_items: "{{ php_fpm_pools }}"

- name: Shut down server if no pools
  service:
    name: "php{{ php_fpm_version }}-fpm"
    state: stopped
    enabled: no
  when: php_fpm_pools|length == 0

# TODO: review security
#- name: Ensure opcache file cache dir exists
#  file:
#    path: "{{ php_fpm_opcache_file_cache }}"
#    owner: root
#    group: root
#    mode: 0777
#    state: directory
#  when: php_fpm_opcache_file_cache_only == 1
