---
- name: "Remove Postgres {{ version }} packages"
  apt:
    pkg: "postgresql-client-{{ version }}"
    state: absent
    purge: true
    update_cache: yes
    cache_valid_time: 3600
  ignore_errors: true
